version: '3'

services: 
  node:
    build: .
    # image: node:alphine
    volumes: 
      - .:/app
    ports: 
      - 3001:3000
    depends_on: 
     - db  

  db:
    image: postgres:alpine    
    environment: 
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    volumes: 
      - .docker/dbdata:/var/lib/postgresql/data